### PR TITLE
Updated to work with Sanity Studio V3

### PR DESCRIPTION
**Pull request by svey-xyz**
Hey! I used this plugin on my V2 desk and loved it. Decided to update it for V3 since I've been using that recently. Everything's working, but you probably want to preserve the V2 branch for those that still use it. And V3 should be added to npm as a new version.

I'm new to public GitHub pull requests, so if I've done anything wrong or you need more info from me just let me know! I am happy to contribute however I can.

### CODE REVIEW

**Comment by evankford** [comment]
Just want to +1 my want for this to go through!

**Comment by cavellblood** [comment]
Would be interested in this PR getting merged if possible.

**Comment by nicktaylor** [comment]
This PR looks good, hopefully it'll get merged. 

@svey-xyz One improvement though, within `defineType` in the schema.tsx and in `components: { ... }` it'd be good if you could add `field: (props) => <div>{props.children}</div>` as that'll get rid of the label, as labels for this aren't required as the note is self explanatory.

**Comment by svey-xyz** [comment]
@nicktaylor Thanks for that piece of advice! I was looking for how to do exactly that and couldn't find it in the documentation.

**Comment by ndimatteo** [comment]
Thank you @svey-xyz for putting in the work on this, and for everyone else's patience! I just pushed up a new version for V3, with some adjustments from what was proposed here ✨ 

Enjoy! And feel free to open new issues for any feedback!

**Pull request closed without merging**
